### ISSUE TITLE
The bug about the disappearance of phone number in the browser

### ISSUE THREAD

**Issue by zswbs35** [Kpure1000/WebExp#1]
Hello! Today, we use the Firefox browser to test the registration and login function. After sending SMS, when we return to the SMS login interface, the phone number entered will disappear. The same operation works well in chrome. What is the cause of this situation and is there any solution?

**Comment by Kpure1000** [comment]
# A Solution
Use ___SESSION__ or ___COOKIE__ to storage the form cache, and load them when back to the history.
